### ISSUE TITLE
Popeye feedback

### ISSUE THREAD

**Issue by klubiniecki** [mishfish123/react-practice#1]
Hey @mishfish123 , thanks for great work!

Few questions - why is Popeye in an array? Do you expect more character? 😉 
I'd rather have all the props passed as one like `person={popeye}` and then have the values extracted in the component itself.
Be mindful of unused imports - best to use linter like `eslint` for this. Unformatted code and unused imports (you import `useState` and never use it) make things prone to errors and hard to read.

🚀

**Comment by mishfish123** [comment]
Thanks Kris. Yes :) you caught me, I was trying to predict the next task. Thanks for your feedback it was very useful. Cheers
